// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmskugdtjfamwnjlyrcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxtc2t1Z2R0amZhbXduamx5cmNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NTU1NDMsImV4cCI6MjA2NzAzMTU0M30.XNfeutFEeHAqJVREi8wNBstY1dQNYUpiBDGzvXhD_nM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});